This is based on "Fast and robust edge extraction in unorganized point clouds" by Dena Bezazian, Josep R. Casas and Javier Ruiz-Hidalgo published in 2015.

The point cloud is in txt format, comma separated with values x, y, z, nx, ny, nz. The normals will not be required in this. The file has 10029 points.

# Part 1: Save the point cloud in a dictionary with serial no starting from 1 as key and value as a list containing a list of x, y, z

In [1]:
file_name = "Part1_STL_10_pow_4_ASCII.txt"

In [2]:
with open(file_name) as file_object:
    lines = file_object.readlines()

In [3]:
data = {}

In [4]:
i = 1
for line in lines:
    items = line.split(",")
    x, y, z = float(items[0]), float(items[1]), float(items[2])
    list_x_y_z = [x, y, z]
    data[i] = list_x_y_z
    i+=1

In [5]:
data[1]

[0.97175932, 0.27299145, 0.60483378]

In [6]:
data[10029]

[0.91336119, 0.46265504, 0.37359932]

In [7]:
len(data)

10029

# Part 2: Calculate nearest neighbours (taking 8 nearest neighbours) based on euclidean distance and add keys to dictionary

In [8]:
import math

In [9]:
def nearest_neighbour(key):
    key_list = []
    dict1 = {}
    for i in range(1, len(data)+1):
        if i == key:
            continue
            
        euclidean_distance = math.sqrt((data[key][0] - data[i][0])**2 + (data[key][1] - data[i][1])**2 + (data[key][2] - data[i][2])**2)
        dict1[i] = euclidean_distance
        
    # Sort dictionary by value in ascending order
    for i in range(8):
        for key1 in dict1.keys():
            min_key = key1
            break
        for key1 in dict1.keys():
            if dict1[key1] < dict1[min_key]:
                min_key = key1
        key_list.append(min_key)
        del dict1[min_key]
    return key_list

In [10]:
for i in range(1, len(data)+1):
    nearest_neighbour_list = nearest_neighbour(i)
    data[i].append(nearest_neighbour_list)    

In [11]:
data[1]

[0.97175932,
 0.27299145,
 0.60483378,
 [2327, 377, 380, 2274, 381, 376, 2391, 378]]

In [12]:
data[500]

[1.13994944, 0.45065624, 0.6041491, [501, 492, 498, 513, 502, 508, 515, 506]]

In [13]:
data[10029]

[0.91336119,
 0.46265504,
 0.37359932,
 [9813, 10028, 10021, 10003, 1059, 1058, 9983, 9995]]

In [14]:
for i in range(1, len(data)+1):
    print(data[i])

[0.97175932, 0.27299145, 0.60483378, [2327, 377, 380, 2274, 381, 376, 2391, 378]]
[1.0082953, 0.30264848, 0.60042644, [379, 432, 188, 189, 384, 349, 392, 350]]
[0.99042088, 0.285272, 0.60121626, [187, 2356, 381, 2391, 376, 189, 377, 2327]]
[0.92371309, 0.23781584, 0.61245215, [191, 2374, 2271, 2251, 2320, 373, 375, 2282]]
[1.15696216, 0.39635032, 0.56963885, [468, 1704, 469, 6, 1718, 470, 1692, 483]]
[1.16360712, 0.39928323, 0.56766462, [1718, 1704, 5, 468, 470, 469, 467, 483]]
[1.04462159, 0.31753415, 0.58908659, [425, 423, 1933, 1953, 2000, 427, 431, 433]]
[1.07764328, 0.34068012, 0.58335984, [430, 429, 1959, 434, 2040, 1972, 1996, 1952]]
[1.09455776, 0.35405838, 0.58115184, [2086, 426, 1957, 2064, 2056, 436, 434, 439]]
[0.36968961, -0.06209164, 0.75066918, [148, 144, 145, 152, 6855, 4497, 4606, 6867]]
[0.67228454, 0.0882892, 0.66878259, [26, 8387, 8389, 12, 8423, 27, 257, 20]]
[0.6860283, 0.08711982, 0.66125137, [27, 256, 257, 26, 11, 23, 196, 25]]
[0.64884114, 0.11025719, 0.6911463

[0.9256748, 0.34426904, 0.46403879, [2219, 2119, 2165, 2208, 2227, 2236, 2197, 2104]]
[0.90630823, 0.33546132, 0.46133623, [2228, 2139, 2216, 2246, 2219, 2155, 2149, 2123]]
[0.88407433, 0.39811882, 0.36263356, [2102, 2136, 2212, 2128, 2209, 2160, 2106, 1290]]
[0.91437906, 0.37429327, 0.41626951, [2242, 2126, 2108, 2169, 2200, 2131, 2122, 1985]]
[0.84018958, 0.35512677, 0.38676995, [2239, 2111, 2173, 2181, 2180, 2220, 2150, 2182]]
[0.93993372, 0.35009748, 0.46689087, [2236, 2197, 2165, 2227, 2002, 2119, 2203, 2068]]
[0.87363744, 0.39221409, 0.36269867, [2106, 2160, 2212, 2102, 2235, 2205, 2202, 2195]]
[0.89628255, 0.3812913, 0.39373836, [2233, 2124, 2237, 2217, 2153, 2177, 2142, 2189]]
[1.00162494, 0.30177674, 0.57583964, [2127, 2107, 2072, 2359, 1981, 1921, 1984, 2356]]
[0.87672633, 0.39743432, 0.35811722, [2160, 2106, 2102, 2209, 2195, 2205, 1290, 2235]]
[0.89927357, 0.34800005, 0.43967891, [2168, 2198, 2109, 2184, 2123, 2246, 2155, 2241]]
[0.86283213, 0.38128626, 0.36909127, [2226, 2

[1.11330104, 0.52354789, 0.50804102, [4071, 4070, 4118, 4060, 4127, 4067, 4048, 4079]]
[1.13487744, 0.50352448, 0.55150366, [4069, 4163, 4109, 4095, 4240, 4068, 4077, 4043]]
[1.06040609, 0.57371062, 0.4057346, [4053, 4054, 4138, 4050, 4051, 4063, 4108, 4064]]
[1.16217566, 0.47797036, 0.60562044, [514, 512, 4241, 4222, 504, 4044, 581, 4081]]
[1.13907933, 0.50237179, 0.57080418, [4043, 4057, 4041, 4046, 6717, 4080, 6751, 4069]]
[1.100631, 0.53693062, 0.48892933, [4079, 4130, 4059, 4114, 4152, 4148, 4037, 4060]]
[1.10409641, 0.53358233, 0.49538836, [4078, 4060, 4130, 4148, 4152, 4114, 4073, 4048]]
[1.14659679, 0.4948813, 0.58391839, [4057, 4092, 4046, 4144, 4081, 4049, 4122, 4041]]
[1.1541158, 0.48618725, 0.59229362, [4144, 4122, 4235, 4241, 4222, 4238, 4092, 4080]]
[1.08864582, 0.54829788, 0.46575317, [4066, 4045, 4058, 4091, 4129, 6737, 4162, 4059]]
[1.10148036, 0.52567434, 0.44934097, [4094, 4105, 4162, 4137, 4099, 4158, 4096, 4085]]
[1.04732442, 0.57888931, 0.35191953, [4145, 4088, 41

[0.91540527, 0.49075246, 0.44483572, [6301, 6241, 6300, 6321, 6347, 6378, 6215, 6383]]
[0.88893372, 0.47002238, 0.45255956, [6302, 6380, 6230, 6292, 6274, 6245, 6210, 6276]]
[0.90541947, 0.49384293, 0.43341592, [6321, 6241, 6383, 6298, 6210, 6215, 6301, 6358]]
[0.91554904, 0.48587367, 0.4513512, [6298, 6378, 6275, 6241, 6321, 6300, 6383, 6246]]
[0.888767, 0.47062501, 0.45164496, [6299, 6380, 6230, 6292, 6274, 6245, 6210, 6276]]
[0.95407242, 0.51116294, 0.44652021, [6206, 6282, 6335, 6339, 6294, 6214, 6365, 6371]]
[0.94553638, 0.52496022, 0.42210296, [6254, 6204, 6229, 6371, 6291, 6212, 6360, 6372]]
[0.921965, 0.44658715, 0.50769222, [6256, 6376, 6281, 6316, 6340, 6364, 6232, 6359]]
[0.90680856, 0.46992102, 0.46586683, [6317, 6292, 6342, 6231, 6380, 6338, 6263, 6221]]
[0.94389385, 0.48178825, 0.47760913, [6284, 6336, 6216, 6257, 6267, 6288, 6310, 6265]]
[0.95625669, 0.46938723, 0.50301248, [6314, 6327, 6313, 6331, 6222, 6279, 6348, 6235]]
[0.9410643, 0.54165626, 0.39687255, [6324, 6330,

[0.52669907, 0.14029942, 0.47416666, [8565, 8582, 8568, 8553, 8537, 8596, 8589, 8563]]
[0.52834493, 0.13859257, 0.47791827, [8564, 8582, 8563, 8568, 8537, 8553, 8596, 8545]]
[0.51119113, 0.15321544, 0.44879445, [8551, 8593, 8595, 8592, 8578, 8532, 8549, 8522]]
[0.59458816, 0.07525215, 0.61203533, [8554, 8538, 8591, 8544, 8559, 8526, 8576, 8541]]
[0.52107447, 0.14376578, 0.46880257, [8582, 8553, 8589, 8564, 8596, 8565, 8537, 8516]]
[0.5532065, 0.11379737, 0.53147691, [8560, 8587, 8573, 8575, 8585, 8533, 8562, 8534]]
[0.60119915, 0.06781949, 0.62916768, [8555, 8571, 8561, 8576, 8559, 8572, 8586, 8599]]
[0.59839457, 0.06928036, 0.62879956, [8576, 8570, 8555, 8559, 8561, 8572, 8599, 8586]]
[0.60239792, 0.06592692, 0.63490325, [8561, 8570, 8555, 8586, 8571, 8576, 8559, 8540]]
[0.54580301, 0.11894268, 0.52394706, [8562, 8598, 8594, 8583, 8569, 8560, 8587, 8547]]
[0.62117636, 0.04886241, 0.66940367, [8558, 35, 36, 8588, 62, 61, 8584, 8601]]
[0.55513084, 0.11005106, 0.54291064, [8585, 8587, 85

# Part 3: Calculate surface variation sigma_p from eigen values of the covariance matrix of each point and append it to dictionary. For flat surface sigma_p tends to zero

In [15]:
import numpy as np

In [16]:
def sigma_p(key):
    covariance_matrix = np.zeros((3,3))
    mean_x, mean_y, mean_z = 0, 0, 0
    for neighbour in data[key][3]:
        mean_x += data[neighbour][0]
        mean_y += data[neighbour][1]
        mean_z += data[neighbour][2]
        
    mean_x = mean_x/8
    mean_y = mean_y/8
    mean_z = mean_z/8
    cov_x_x = 0
    cov_y_y = 0
    cov_z_z = 0
    cov_x_y = 0
    cov_x_z = 0
    cov_y_z = 0
    
    for neighbour in data[key][3]:
            cov_x_x += (data[neighbour][0] - mean_x)**2
            cov_y_y += (data[neighbour][1] - mean_y)**2
            cov_z_z += (data[neighbour][2] - mean_z)**2
            cov_x_y += (data[neighbour][0] - mean_x)*(data[neighbour][1] - mean_y)
            cov_x_z += (data[neighbour][0] - mean_x)*(data[neighbour][2] - mean_z)
            cov_y_z += (data[neighbour][1] - mean_y)*(data[neighbour][2] - mean_z)
            
    covariance_matrix[0,0] = cov_x_x/7
    covariance_matrix[1,1] = cov_y_y/7
    covariance_matrix[2,2] = cov_z_z/7
    covariance_matrix[0,1] = cov_x_y/7
    covariance_matrix[1,0] = cov_x_y/7
    covariance_matrix[0,2] = cov_x_z/7
    covariance_matrix[2,0] = cov_x_z/7
    covariance_matrix[1,2] = cov_y_z/7
    covariance_matrix[2,1] = cov_y_z/7
    
    eigenValue, eigenVector = np.linalg.eig(covariance_matrix)
    
    sigmaP = min(eigenValue)/sum(eigenValue)
    
    return sigmaP

In [17]:
for i in range(1, len(data)+1):
    sigma = sigma_p(i)
    data[i].append(sigma)

In [18]:
data[1]

[0.97175932,
 0.27299145,
 0.60483378,
 [2327, 377, 380, 2274, 381, 376, 2391, 378],
 0.025583745672222952]

In [19]:
data[10029]

[0.91336119,
 0.46265504,
 0.37359932,
 [9813, 10028, 10021, 10003, 1059, 1058, 9983, 9995],
 0.15371702893223815]

Check for minimum and maximum sigma

In [20]:
min_sigma = data[1][4]
max_sigma = data[1][4]
for i in range(2, len(data)+1):
    sigma = data[i][4]
    if sigma < min_sigma:
        min_sigma = sigma
    if sigma > max_sigma:
        max_sigma = sigma

In [21]:
min_sigma, max_sigma

(1.4438635066634446e-14, 0.29219662397315455)

In [22]:
for i in range(1, len(data)+1):
    print(data[i])

[0.97175932, 0.27299145, 0.60483378, [2327, 377, 380, 2274, 381, 376, 2391, 378], 0.025583745672222952]
[1.0082953, 0.30264848, 0.60042644, [379, 432, 188, 189, 384, 349, 392, 350], 1.5397591394621766e-12]
[0.99042088, 0.285272, 0.60121626, [187, 2356, 381, 2391, 376, 189, 377, 2327], 0.032003586908823815]
[0.92371309, 0.23781584, 0.61245215, [191, 2374, 2271, 2251, 2320, 373, 375, 2282], 0.05236423955086767]
[1.15696216, 0.39635032, 0.56963885, [468, 1704, 469, 6, 1718, 470, 1692, 483], 0.03653499092361289]
[1.16360712, 0.39928323, 0.56766462, [1718, 1704, 5, 468, 470, 469, 467, 483], 0.02721513674954841]
[1.04462159, 0.31753415, 0.58908659, [425, 423, 1933, 1953, 2000, 427, 431, 433], 0.028730966010923887]
[1.07764328, 0.34068012, 0.58335984, [430, 429, 1959, 434, 2040, 1972, 1996, 1952], 0.011407646213420585]
[1.09455776, 0.35405838, 0.58115184, [2086, 426, 1957, 2064, 2056, 436, 434, 439], 0.03422502642983762]
[0.36968961, -0.06209164, 0.75066918, [148, 144, 145, 152, 6855, 4497, 4

[0.90374166, 0.40084404, 0.37354869, [1995, 1973, 1946, 2148, 2029, 1951, 2136, 1800], 1.339137593297369e-12]
[1.02858758, 0.33053505, 0.55793071, [2050, 1964, 1940, 1967, 2035, 2081, 1988, 2044], 2.891647281133192e-12]
[0.93496025, 0.38450649, 0.41802073, [1931, 2048, 1961, 2169, 2200, 1994, 1985, 2037], 5.027041646828049e-13]
[1.06795251, 0.36842945, 0.53716016, [1945, 2088, 1919, 1998, 1982, 1950, 2010, 2066], 1.1281875583317368e-12]
[1.0553298, 0.34403363, 0.55990666, [2025, 1926, 1987, 1935, 2046, 2018, 1988, 1949], 1.6152964307967658e-12]
[0.97426939, 0.34495816, 0.49894875, [2065, 2055, 2115, 2099, 2003, 2078, 2047, 2093], 2.2272120728128506e-12]
[1.04723716, 0.3369422, 0.56325853, [1988, 1949, 1967, 2023, 1926, 2044, 2046, 2050], 2.2445930891761838e-12]
[1.02680135, 0.38745758, 0.48183277, [2034, 1939, 2005, 2001, 2013, 2036, 1848, 1956], 1.328250775100178e-12]
[0.89570981, 0.40874025, 0.35725537, [1951, 1737, 1754, 1800, 1973, 1289, 2205, 2136], 4.4735824861363916e-05]
[1.0785

[0.33141097, -0.06261787, 0.74140376, [4393, 4400, 4433, 1522, 1541, 4277, 1540, 4561], 0.06688164083878294]
[0.29572308, 0.00731392, 0.62322867, [4430, 4367, 4376, 6874, 4356, 4432, 4359, 4413], 0.05615529312561846]
[0.26804516, 0.00050073, 0.61178023, [1544, 4423, 1542, 4334, 4287, 4414, 1521, 4372], 0.10734354546545265]
[0.24468964, 0.06038281, 0.51589715, [4278, 4327, 4338, 4364, 751, 4330, 4295, 652], 0.024677022841143082]
[0.302279, 0.10260344, 0.50287485, [4431, 4377, 4290, 4282, 816, 4298, 757, 747], 0.07348142052462439]
[0.26181981, 0.03372362, 0.56354576, [4410, 4293, 4385, 4323, 4333, 4435, 4331, 4305], 7.064919742304846e-13]
[0.3258464, 0.11118899, 0.50896543, [4335, 4489, 4703, 4759, 4716, 4298, 4475, 746], 0.0016664388284593843]
[0.25760284, 0.0547139, 0.53286195, [4427, 4364, 6881, 6895, 4421, 4341, 4370, 6864], 0.10642052285057492]
[0.33004853, 0.05603461, 0.584521, [4547, 4452, 4483, 4490, 4596, 6981, 6988, 4434], 0.02696675235256114]
[0.28590047, 0.03828526, 0.5753008

[0.87360692, 0.49029467, 0.4146308, [6353, 6323, 6320, 6273, 6295, 6228, 6207, 6379], 1.5580149982651914e-12]
[0.94183701, 0.4221226, 0.55447841, [6233, 6354, 6259, 6328, 6322, 6311, 6253, 6270], 2.664592100420307e-12]
[0.96209782, 0.45621327, 0.52462471, [6370, 6244, 6369, 6242, 6337, 6345, 6278, 6385], 2.3720368094357904e-12]
[0.9678784, 0.42222336, 0.57353914, [6211, 6355, 6238, 6431, 6283, 6315, 6568, 6557], 3.015675551693068e-12]
[0.94848645, 0.41839084, 0.5642817, [6322, 6270, 6377, 6259, 6354, 6250, 6312, 6209], 8.779046034185962e-13]
[0.94408453, 0.52271593, 0.42398125, [6204, 6304, 6229, 6371, 6212, 6372, 6360, 6365], 4.296918200076679e-12]
[0.9301911, 0.40920824, 0.5628612, [6213, 6312, 6293, 6209, 6136, 6064, 6184, 6147], 7.362149837389547e-13]
[0.92598999, 0.44553989, 0.51203454, [6305, 6316, 6340, 6376, 6281, 6272, 6364, 6232], 8.34998369559547e-13]
[0.93605459, 0.48400828, 0.46891484, [6288, 6265, 6216, 6246, 6275, 6307, 6378, 6280], 3.298780302708395e-12]
[0.96635103, 0.

[0.49333939, 0.07755416, 0.54114175, [7817, 7821, 7861, 7823, 7799, 7875, 7871, 7782], 0.0072771496808385445]
[0.47049314, 0.09541419, 0.49573782, [7819, 7844, 7834, 7870, 7866, 7852, 7851, 7869], 0.0014147518691757593]
[0.53012264, 0.0403354, 0.61334825, [7835, 7848, 7838, 7831, 7863, 7856, 7800, 7791], 0.005882276339701907]
[0.46052435, 0.10893109, 0.47653174, [7850, 7798, 7854, 7852, 7865, 7833, 7847, 7778], 0.0034779912900189383]
[0.52525806, 0.04504592, 0.60377657, [7848, 7813, 7856, 7845, 7829, 7806, 7862, 7863], 0.0042015109714586265]
[0.50375414, 0.06607731, 0.56148696, [7841, 7809, 7815, 7810, 7857, 7797, 7804, 7843], 0.002993446444767676]
[0.45364079, 0.11714385, 0.46315113, [7847, 7814, 7846, 7865, 7830, 7795, 7868, 7849], 0.0039184591228453745]
[0.47545975, 0.09182598, 0.50563943, [7851, 7866, 7828, 7819, 7870, 7839, 7853, 7796], 0.005014376597513624]
[0.53287178, 0.03693238, 0.61867923, [7838, 7829, 7800, 7848, 7802, 7863, 7831, 7879], 0.0032470941908320987]
[0.55417085, 0

[0.85530275, 0.39515948, 0.40963408, [9654, 9656, 9646, 9647, 9675, 9673, 9638, 9640], 0.006535558594272294]
[0.90573448, 0.34762874, 0.50892442, [9661, 9655, 9674, 9677, 9632, 9645, 9712, 9689], 0.03155415815693142]
[0.8664254, 0.38482615, 0.43161666, [9671, 9691, 9688, 9648, 9699, 9680, 9633, 9619], 0.017520113780562677]
[0.87781626, 0.37539902, 0.45478061, [9649, 9683, 9634, 9623, 9617, 9612, 9707, 9630], 0.03694199411396378]
[0.91914332, 0.33215868, 0.53482163, [9650, 9690, 9670, 9684, 9658, 9703, 9642, 9714], 0.020286392383383964]
[0.93330818, 0.32003304, 0.56286132, [9685, 9657, 9694, 9695, 9693, 9652, 9659, 9629], 0.003487892637741975]
[0.89423174, 0.35641527, 0.48581919, [9682, 9686, 9700, 9698, 9689, 9704, 9636, 9645], 0.010756744126837964]
[0.91479462, 0.33651176, 0.52628016, [9690, 9642, 9667, 9677, 9703, 9650, 9627, 9720], 0.05212015913155717]
[0.86527842, 0.38417709, 0.42882073, [9665, 9691, 9688, 9699, 9680, 9648, 9673, 9633], 0.008430087628960765]
[0.84056956, 0.40713602

# 3D visualization considering sigma value less or equal to 0.05 as edge points

In [23]:
import ipyvolume as ipv

In [102]:
x, y, z = np.empty(0), np.empty(0), np.empty(0)

In [103]:
x

array([], dtype=float64)

In [104]:
for key, value in data.items():
    if value[4] < 0.001:
        x = np.append(x, value[0])
        y = np.append(y, value[1])
        z = np.append(z, value[2])

In [105]:
x, y, z

(array([1.0082953 , 0.6860283 , 0.67243326, ..., 0.83431983, 0.83082342,
        0.81426764]),
 array([0.30264848, 0.08711982, 0.12130205, ..., 0.37265268, 0.37408972,
        0.38733959]),
 array([0.60042644, 0.66125137, 0.68443817, ..., 0.41246879, 0.41115877,
        0.38747355]))

In [106]:
len(x)

4659

In [1]:
fig = ipv.figure()
scatter = ipv.scatter(x, y, z, color = 'red', size=0.75, marker='sphere')
ipv.show()

NameError: name 'ipv' is not defined

In [42]:
N = 10
x, y, z = np.random.normal(0, 1, (3, N))

In [43]:
x

array([ 0.5436381 , -0.78685276, -1.35805416, -0.55244572, -0.80638321,
        0.23731369, -0.3275217 , -1.23221855,  1.88672242,  0.45114837])

In [51]:
ipv.scatter?